### ISSUE TITLE
Linking Replicate filter to Align Samples - error in Replicate Filter metadata output format

### ISSUE THREAD

**Issue by M-R-JONES** [computational-metabolomics/dimspy#34]
When running the dimspy processing pipeline on the Galaxy server, an error arises in running linking the "Replicate Filter" and "Align Samples" tools. This error is believed to be linked to incorrect formatting of the "Sample Metadata" file output from the "Replicate Filter" tool.

Example error log:

```
Fatal error: Exit code 1 ()
/gpfs/apps/galaxy/viantm-dev/galaxy/tool_dependencies/_conda/envs/__dimspy@1.0.0/lib/python2.7/site-packages/dimspy/experiment.py:138: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

Traceback (most recent call last):
  File "/gpfs/apps/galaxy/viantm-dev/galaxy/tool_dependencies/_conda/envs/__dimspy@1.0.0/bin/dimspy", line 11, in <module>
    load_entry_point('dimspy==1.0.0', 'console_scripts', 'dimspy')()
  File "/gpfs/apps/galaxy/viantm-dev/galaxy/tool_dependencies/_conda/envs/__dimspy@1.0.0/lib/python2.7/site-packages/dimspy/__main__.py", line 463, in main
    ncpus=args.ncpus)
  File "/gpfs/apps/galaxy/viantm-dev/galaxy/tool_dependencies/_conda/envs/__dimspy@1.0.0/lib/python2.7/site-packages/dimspy/tools.py", line 262, in align_samples
    fl = check_metadata(filelist)
  File "/gpfs/apps/galaxy/viantm-dev/galaxy/tool_dependencies/_conda/envs/__dimspy@1.0.0/lib/python2.7/site-packages/dimspy/experiment.py", line 141, in check_metadata
    idxs_replicates = idxs_reps_from_filelist(fm["replicate"])
  File "/gpfs/apps/galaxy/viantm-dev/galaxy/tool_dependencies/_conda/envs/__dimspy@1.0.0/lib/python2.7/site-packages/dimspy/experiment.py", line 254, in idxs_reps_from_filelist
    raise ValueError("Incorrect numbering for replicates. Row {}".format(i))
ValueError: Incorrect numbering for replicates. Row 1
```

Based on the above, it seems that the "replicate" column of the "Sample Metadata" file may be in an inappropriate format for subsequent use with the "Align Samples" tool.

**Comment by M-R-JONES** [comment]
Example output from "Replicate Filter"

[Galaxy12-Blank_Filter_on_data_7__Peak_intensity_matrix_comprehensive.txt](https://github.com/computational-metabolomics/dimspy/files/1470754/Galaxy12-Blank_Filter_on_data_7__Peak_intensity_matrix_comprehensive.txt)
